
import graph_search_euclidean_crosspath
file = open('output0.txt', 'a')
g = graph_search_euclidean_crosspath.GridMap('./map0.txt')
[[path, action_path],visited]=graph_search_euclidean_crosspath.a_star_search(g.init_pos ,g.goal, g.transition , g.is_goal, graph_search_euclidean_crosspath._ACTIONS_2)
print(path)
print(action_path)
print(visited)
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map0: path        = "+str(path) + "\n")
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map0:Action_path = "+str(action_path) + "\n")
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map0: visited     = "+str(visited) + "\n")
g.display_map(path,visited,"Project-1_4_4.1/4.3_A*- Hearsitic as Euclidean on map0")
file.close()

import graph_search_euclidean_crosspath
file = open('output1.txt', 'a')
g = graph_search_euclidean_crosspath.GridMap('./map1.txt')
[[path, action_path],visited]=graph_search_euclidean_crosspath.a_star_search(g.init_pos ,g.goal, g.transition , g.is_goal, graph_search_euclidean_crosspath._ACTIONS_2)
print(path)
print(action_path)
print(visited)
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map1: path        = "+str(path) + "\n")
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map1: action_path = "+str(action_path) + "\n")
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map1: visited     = "+str(visited) + "\n")
g.display_map(path,visited,"Project-1_4_4.1/4.3_A*- Hearsitic as Euclidean on map1")
file.close()

import graph_search_euclidean_crosspath
file = open('output2.txt', 'a')
g = graph_search_euclidean_crosspath.GridMap('./map2.txt')
[[path, action_path],visited]=graph_search_euclidean_crosspath.a_star_search(g.init_pos ,g.goal, g.transition , g.is_goal, graph_search_euclidean_crosspath._ACTIONS_2)
print(path)
print(action_path)
print(visited)
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map2: path        = "+str(path) + "\n")
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map2 action_path = "+str(action_path) + "\n")
file.write("Project-1_4_4.1_A*- Hearsitic as Euclidean on map2  visited     = "+str(visited) + "\n")
g.display_map(path,visited,"Project-1_4_4.1/4.3_A*- Hearsitic as Euclidean on map2")
file.close()
